### ISSUE TITLE
DataTable prop pageSize does not work as expected

### ISSUE THREAD

**Issue by RaBorn-Teselagen** [TeselaGen/teselagen-react-components#290] opened 2022-10-20 17:00 UTC
Related to [issue #9727](https://github.com/TeselaGen/lims/issues/9724) and this [PR](https://github.com/TeselaGen/lims/pull/9967):

As described on 9727, not all columns are shown on smart mapper dialog. The problem was that `pageSize` prop of TRC DataTable component do nothing and was set it as default (25 rows).

**Comment by tnrich** [comment] 2022-12-01 18:38
@RaBorn-Teselagen is this completed?

**Comment by tnrich** [comment] 2022-12-01 18:42
@RaBorn-Teselagen into looking into the related issue on lims, I believe that the issue is solved there via this change: 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/2730609/205134034-fe52b8af-4092-4ae3-9dcb-7fd4c01faa82.png">

However, the reason it wasn't working beforehand was due to an incorrect passing of pageSize as a top level prop to the datatable. Instead, pageSize needs to be passed within a defaults prop like so: `defaults={{pageSize: XX}}`

For example here: 

<img width="644" alt="image" src="https://user-images.githubusercontent.com/2730609/205134288-35d4f1d5-0664-4f8c-acfc-f56cc4f6a356.png">

Closing as the issue has been fixed and was already working in TRC

**Closed by tnrich** 2022-12-01 18:43 UTC
Labels: bug
